### ISSUE TITLE
Feature request: Change error code prefix to multiple characters

### ISSUE THREAD

**Issue by wwuck** [msabramo/flake8-exact-pin#4]
I would like to request changing the error code prefix from `P` to `PIN`.

This plugin is currently conflicting with `flake8-string-format` which also uses the `P` prefix for flake8 error codes.

As of flake8 v3.0, plugins are no longer required to have error codes exactly four characters long and the [flake8 documentation](https://flake8.pycqa.org/en/3.8.3/plugin-development/registering-plugins.html) recommends using a longer prefix to avoid conflicts with other plugins:
```
Flake8 requires each entry point to be unique amongst all plugins installed in the users environment. Selecting an entry point that is already used can cause plugins to be deactivated without warning!

Please Note: Your entry point does not need to be exactly 4 characters as of Flake8 3.0. Consider using an entry point with 3 letters followed by 3 numbers (i.e. ABC123 ).
```

**Comment by msabramo** [comment]
Thanks, @wwuck!

**Comment by msabramo** [comment]
Released in https://pypi.org/project/flake8-exact-pin/0.1.0/
